version: '3.8'
services:
    mysql-db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: autos10a
            MYSQL_USER: autos
            MYSQL_PASSWORD: passwordautos
        volumes:
            - /mysql-data:/var/lib/mysql
        networks:
            - proyecto-network

    app:
        build:
            context: ./gpds-autos
            dockerfile: Dockerfile
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://mysql-sdb:3306/autos10a
            SPRING_DATASOURCE_USERNAME: autos
            SPRING_DATASOURCE_PASSWORD: passwordautos
            SPRING_JPA_HIBERNATE_DDL_AUTO: update
        ports:
            - "8081:8081"
        depends_on:
            - mysql-db
        networks:
            - proyecto-network

    client:
        build:
            context: ./gpds-ui
            dockerfile: Dockerfile
        ports:
            - "8082:80"
        volumes:
            - ./nginx.conf:/etc/nginx.conf
        networks:
            - proyecto-network

networks:
    proyecto-network:
        driver: bridge
